### ISSUE TITLE
collected items

### ISSUE THREAD

**Issue by lihaicheng7003** [LUMC/pytest-workflow#181]
Why is it shown "collected 2 items", shouldn't it be 1 item?
```
- name: Touch a file
  command: touch test.file
  files:
    - path: test.file
```

![image](https://github.com/LUMC/pytest-workflow/assets/61043072/7d90c729-de70-4c5b-9c52-2f6f73a454b0)
