### ISSUE TITLE
Feature request: Allow wildcard in path

### ISSUE THREAD

**Issue by stianlagstad** [LUMC/pytest-workflow#188]
I have a test like this:
```yaml
- name: "Test something"
  command: my_command
  files:
    - path: logfile.txt
```

But I want to change how I produce the `logfile.txt` so that the name includes the date, like this: `logfile-2023-11-30.txt`. This causes my above assertion to fail, but I'd still like to make this work somehow. I would like to do something like this:
```yaml
- name: "Test something"
  command: my_command
  files:
    - path: logfile*.txt
```

Or similar. It would be very useful is some kind of wildcarding would work for path assertions.
